apiVersion: v2
appVersion: "1.0"
description: A Helm chart for redash
name: redash-helm
version: 0.1.2
keywords:
  - redash
  - redash-helm
  - helm
  - chart
  - helm-chart
  - kubernetes
maintainers:
- name: pparthesh

dependencies:
  - name: redis
    version: 10.7.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 8.10.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
